### PR TITLE
Add image map support

### PR DESCRIPTION
**Pull request by stephane-mori**
Hi, 

Some plantuml representation contains hyperlinks. Those hyperlinks trig
the generation of a map tag. These map tag is linked to the generated
image by usemap attribute which refer to the map name.

This feature seems to not be existing in current version. So this PR tried to add it.

I am not a python developper, it was the first time I manipulate python. 
However, I prefer submit this PR to explain what's my need.

I am at your disposition.

Regards,
Stéphane MORI

### CODE REVIEW

**Comment by mikitex70** [comment]
Hi @stephane-mori, thanks for your PR.
It is now merged as commit eb2d81d.
I've made some small fixes:
* the test was failing checking area coords, probably caused by different plantuml versions
* the image map are now rendered only for png images, speeding up rendering for non png diagram formats
* image maps are generated only when rendering png using local plantuml; when using a remote server it is not possible

**Comment by stephane-mori** [comment]
Hi @mikitex70,

When do you plan to make a new release with this new feature ?

Regards,
Stéphane MORI

**Comment by mikitex70** [comment]
As soon as I have enough free time, I hope in a couple of days...

**Comment by mikitex70** [comment]
Merged in the `master` branch and released as version `3.5.0`.
Thanks for your PR, I was not aware of the `-pipemap` parameter.

**Pull request closed without merging**
